FROM python:3.11-slim

RUN apt-get update && apt-get install -y libpq-dev python3-dev

WORKDIR /app

COPY requirements-streamlit.txt ./
COPY moodmeter/services/dashboard.py moodmeter/modules/ moodmeter/utils/ lib/ ./moodmeter/

RUN pip install --upgrade pip
RUN pip install -r requirements-streamlit.txt

ENV PYTHONPATH=/app

EXPOSE 8501

CMD ["streamlit", "run", "moodmeter/services/dashboard.py"]
