FROM python:3.11-slim

RUN apt-get update && apt-get install -y libpq-dev python3-dev

WORKDIR /app

COPY requirements-bot.txt ./
COPY moodmeter/services/telegram_bot.py moodmeter/modules/ moodmeter/utils/ lib/ ./moodmeter/

RUN pip install --upgrade pip
RUN pip install -r requirements-bot.txt

ENV PYTHONPATH=/app

CMD ["python3", "moodmeter/services/telegram_bot.py"]

