version: '3'

services:
  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    depends_on:
      - bot

  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    volumes:
      - .:/app
